name: Setup
description: Setup mise, cache pnpm store, and install dependencies

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        install: true

    - name: Get pnpm store directory
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      shell: bash

    - name: Cache pnpm store
      uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
      with:
        key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        path: ${{ env.STORE_PATH }}
        restore-keys: pnpm-${{ runner.os }}-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --ignore-scripts
      shell: bash

    - name: Rojo Sync
      run: pnpm rojo-sync
      shell: bash
