# yaml-language-server:
# $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

version: "0.2"
language: en

words:
  - claudecode
  - exclusify
  - interactable
  - jecs
  - ocale
  - oxlint
  - pcall
  - rbxl
  - rojo
  - thumbstick
  - typetest
  - unstub
  - wasd
  - worktree
  - worktrees
  - worktrunk
