[env]
_.path = [
  '{{config_root}}/node_modules/.bin',
  '{{cwd}}/node_modules/.bin',  
]
_.file = { path = ".env", redact = true }

[settings]
experimental = true

[settings.node]
corepack = true

[tools]
"github:luau-lang/lute" = "1.0.0"
"github:rojo-rbx/rojo" = "v7.7.0-rc.1"
"npm:@antfu/ni" = "latest"
"npm:corepack" = "latest"
hk = "latest"
node = { version = "lts", postinstall = "corepack enable" }
pkl = "latest"
