type Event = unknown;

export type EventType =
	| "abort"
	| "animationEnd"
	| "animationIteration"
	| "animationStart"
	| "blur"
	| "canPlay"
	| "canPlayThrough"
	| "change"
	| "click"
	| "compositionEnd"
	| "compositionStart"
	| "compositionUpdate"
	| "contextMenu"
	| "copy"
	| "cut"
	| "dblClick"
	| "doubleClick"
	| "drag"
	| "dragEnd"
	| "dragEnter"
	| "dragExit"
	| "dragLeave"
	| "dragOver"
	| "dragStart"
	| "drop"
	| "durationChange"
	| "emptied"
	| "encrypted"
	| "ended"
	| "error"
	| "focus"
	| "focusIn"
	| "focusOut"
	| "gotPointerCapture"
	| "input"
	| "invalid"
	| "keyDown"
	| "keyPress"
	| "keyUp"
	| "load"
	| "loadedData"
	| "loadedMetadata"
	| "loadStart"
	| "lostPointerCapture"
	| "mouseDown"
	| "mouseEnter"
	| "mouseLeave"
	| "mouseMove"
	| "mouseOut"
	| "mouseOver"
	| "mouseUp"
	| "paste"
	| "pause"
	| "play"
	| "playing"
	| "pointerCancel"
	| "pointerDown"
	| "pointerEnter"
	| "pointerLeave"
	| "pointerMove"
	| "pointerOut"
	| "pointerOver"
	| "pointerUp"
	| "popState"
	| "progress"
	| "rateChange"
	| "reset"
	| "resize"
	| "scroll"
	| "seeked"
	| "seeking"
	| "select"
	| "stalled"
	| "submit"
	| "suspend"
	| "timeUpdate"
	| "touchCancel"
	| "touchEnd"
	| "touchMove"
	| "touchStart"
	| "transitionCancel"
	| "transitionEnd"
	| "transitionRun"
	| "transitionStart"
	| "volumeChange"
	| "waiting"
	| "wheel";

export type FireFunction = (element: Instance, event: Event) => boolean;
// oxlint-disable-next-line typescript/no-empty-object-type
export type FireObject = Record<EventType, (element: Instance, options?: {}) => boolean>;

export const fireEvent: FireFunction & FireObject;
