#!/usr/bin/env bun

import assert from "node:assert";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const PROJECT_ROOT = path.resolve(import.meta.dirname, "..");
const NODE_MODULES = path.join(PROJECT_ROOT, "node_modules");
const PATCH_DIR = path.join(PROJECT_ROOT, "patches");

const SOURCE_PROJECT = path.join(NODE_MODULES, "@rbxts-js.project.json");
const OUTPUT_PROJECT = path.join(NODE_MODULES, "@rbxts-js-native.project.json");
const WRAPPER_SOURCE = path.join(NODE_MODULES, "@rbxts.project.json");
const WRAPPER_PROJECT = path.join(NODE_MODULES, "@rbxts-native.project.json");
const OUTPUT_DIR = path.join(NODE_MODULES, ".native-store-hook");

/**
 * The `@rbxts` wrappers the native mount needs beside its own `@rbxts-js`.
 * Everything else a natively-mounted module imports — `@rbxts/flux` above all —
 * is deliberately left out, so the walk up from the native subtree falls
 * through to the one global copy and both legs share it.
 *
 * These are copied rather than mounted from the store a second time. Roblox-ts
 * maps a source path back to one instance path, so mounting a directory twice
 * makes `@rbxts/react` ambiguous and every spec in the game build risks
 * compiling against whichever mount it picks.
 */
const WRAPPER_PACKAGES = ["react", "react-roblox"];

/**
 * The react-lua packages Roblox/react-luau#24 touches, as Rojo instance name ->
 * patch file. The react package only forwards to
 * `dispatcher.useSyncExternalStore`, which the reconciler installs, so all
 * three are copied and patched together or the stack is inconsistent.
 */
const PATCHED_PACKAGES = new Map([
	["React", "@rbxts-js__react@17.3.7-ts.1.patch"],
	["ReactReconciler", "@rbxts-js__react-reconciler@17.3.7-ts.1.patch"],
	["Shared", "@rbxts-js__shared@17.3.7-ts.1.patch"],
]);

interface ProjectNode {
	$className?: string;
	$path?: string;
	[child: string]: ProjectNode | string | undefined;
}

interface ProjectFile {
	name: string;
	globIgnorePaths?: Array<string>;
	tree: ProjectNode;
}

function assertProjectFile(value: unknown, file: string): asserts value is ProjectFile {
	assert.ok(
		typeof value === "object" &&
			value !== null &&
			"tree" in value &&
			typeof value.tree === "object" &&
			value.tree !== null,
		`${file} is malformed. It is generated by generate-rojo-node-modules.ts during install.`,
	);
}

/**
 * Reads one of the generated Rojo maps, which already hold a resolved `$path`
 * per package.
 *
 * @param file - Absolute path to the generated project file.
 * @returns The parsed project.
 */
function readProject(file: string): ProjectFile {
	assert.ok(
		fs.existsSync(file),
		`${file} is missing. It is generated by generate-rojo-node-modules.ts during install.`,
	);

	const parsed: unknown = JSON.parse(fs.readFileSync(file, "utf8"));
	assertProjectFile(parsed, file);
	return parsed;
}

/**
 * Resolves one package's `$path` out of a generated project.
 *
 * @param project - The parsed project to read from.
 * @param instance - The package's Rojo instance name, e.g. `React`.
 * @param file - The project's path, for the failure message.
 * @returns The package's `$path`, relative to `node_modules`.
 */
function pathOf(project: ProjectFile, instance: string, file: string): string {
	const node = project.tree[instance];
	assert.ok(
		typeof node === "object" && typeof node.$path === "string",
		`${instance} is missing a $path in ${file}`,
	);
	return node.$path;
}

/**
 * Copies one package out of the pnpm store and applies its patch.
 *
 * @param instance - The directory to write under `.native-store-hook`.
 * @param relativePath - Its `$path` in the generated map, relative to
 *   `node_modules`.
 * @param patch - Patch to apply once copied. Omitted for packages that are
 *   copied only to keep every mounted directory distinct.
 * @returns The copy's `$path`, relative to `node_modules`.
 */
function materialize(instance: string, relativePath: string, patch?: string): string {
	const source = path.resolve(NODE_MODULES, relativePath);
	const destination = path.join(OUTPUT_DIR, instance);

	fs.rmSync(destination, { force: true, recursive: true });
	fs.cpSync(source, destination, { recursive: true });

	if (patch === undefined) {
		return path.relative(NODE_MODULES, destination).split(path.sep).join("/");
	}

	// `git apply` rather than a hand-rolled patcher: the patches are split
	// straight out of the upstream PR, so they must be read by the same tool
	// that produced them. It runs from the repo root with `--directory`,
	// because inside a work tree it resolves patch paths from the top level
	// and silently skips anything outside the current one.
	execFileSync(
		"git",
		[
			"apply",
			"--directory",
			path.relative(PROJECT_ROOT, destination).split(path.sep).join("/"),
			path.join(PATCH_DIR, patch),
		],
		{ cwd: PROJECT_ROOT, stdio: "pipe" },
	);

	return path.relative(NODE_MODULES, destination).split(path.sep).join("/");
}

const SOURCE = readProject(SOURCE_PROJECT);
const NATIVE: ProjectFile = { ...SOURCE, tree: { ...SOURCE.tree } };

for (const [instance, patch] of PATCHED_PACKAGES) {
	const relativePath = pathOf(SOURCE, instance, SOURCE_PROJECT);
	NATIVE.tree[instance] = { $path: materialize(instance, relativePath, patch) };
}

const WRAPPERS = readProject(WRAPPER_SOURCE);
const WRAPPER_TREE: ProjectNode = { $className: "Folder" };
for (const name of WRAPPER_PACKAGES) {
	const relativePath = pathOf(WRAPPERS, name, WRAPPER_SOURCE);
	WRAPPER_TREE[name] = { $path: materialize(`@rbxts+${name}`, relativePath) };
}

fs.writeFileSync(
	WRAPPER_PROJECT,
	`${JSON.stringify({ ...WRAPPERS, tree: WRAPPER_TREE }, undefined, "\t")}\n`,
);

fs.writeFileSync(OUTPUT_PROJECT, `${JSON.stringify(NATIVE, undefined, "\t")}\n`);
console.log(
	`✓ wrote node_modules\\@rbxts-js-native.project.json (${PATCHED_PACKAGES.size} patched)`,
);
